### ISSUE TITLE
The following error occurs when running AFL on my Pixel 6 phone

### ISSUE THREAD

**Issue by git00000000001** [quarkslab/android-fuzzing#1]
The following error occurs when running AFL on my Pixel 6 phone。
By the way，I am compiling AFL on Macos。
error message:

[-] Hmm, looks like the target binary terminated before we could complete a
handshake with the injected code. You can try the following:

    - The target binary crashes because necessary runtime conditions it needs
      are not met. Try to:
      1. Run again with AFL_DEBUG=1 set and check the output of the target
         binary for clues.
      2. Run again with AFL_DEBUG=1 and 'ulimit -c unlimited' and analyze the
         generated core dump.

    - Possibly the target requires a huge coverage map and has CTORS.
      Retry with setting AFL_MAP_SIZE=10000000.

Otherwise there is a horrible bug in the fuzzer.
Poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : afl_fsrv_start(), /Volumes/CODE/FUZZ/QUARKSLAB/android-fuzzing/AFLplusplus/AFLplusplus-4.06c/src/afl-forkserver.c:1385

**Comment by Ha0ris** [comment]
Hello, it's probably an error in your harness/configuration. By the way, there is no support on this repo which just serves as a code base for the blogpost. For any problem/question about the use of AFL++ you should contact the community (github/discord).
